# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vasyl-babynets
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v1.0.6-78b2636"
  arch: amd64
secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN