# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: vbabynets
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0.7-d8099fa"
  arch: amd64
secret:
  name: kbot
  tokenKey: token
  tokenName: TELE_TOKEN